version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: DeskBooking.Api/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
    - ConnectionStrings__DeskBookingDatabase=Host=${DB_HOST};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

  frontend:
    build:
      context: ./src/frontend/DeskBooking.Web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5